import lazy_loader as lazy

__getattr__, __dir__, __all__ = lazy.attach(
    __name__,
    submod_attrs={
        "_python": [
            "ColorFormat",
            "GameMode",
            "GameRule",
            "Identifier",
            "Logger",
            "OfflinePlayer",
            "Player",
            "Registry",
            "Server",
            "Skin",
            "__minecraft_version__",
            "actor",
            "attribute",
            "ban",
            "block",
            "boss",
            "command",
            "damage",
            "enchantments",
            "event",
            "form",
            "inventory",
            "lang",
            "level",
            "map",
            "nbt",
            "permissions",
            "plugin",
            "potion",
            "scheduler",
            "scoreboard",
            "util",
        ],
        "_version": ["__version__"],
    },
)
