// Generated by scripts/dump_symbols.py for BDS 1.26.36 (linux). DO NOT EDIT.
// clang-format off
// NOLINTBEGIN

#pragma once

#include <array>
#include <cstddef>
#include <string_view>
#include <utility>

namespace endstone::runtime {

static constexpr std::array<std::pair<std::string_view, std::size_t>, 64> symbols = {{
    {"BlockState::StateListNode::mHead", 234492032},
    {"Enchant::mEnchants", 234332496},
    {"getI18n::result", 233014248},
    // Actor
    {"_ZN5Actor10teleportToERK4Vec3biib", 163948656},
    // ActorFactory
    {"_ZN12ActorFactory18createSpawnedActorERK25ActorDefinitionIdentifierP5ActorRK4Vec3RK4Vec2", 160538624},
    // BatchedNetworkPeer
    {"_ZN18BatchedNetworkPeer10sendPacketERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEN11NetworkPeer11ReliabilityE15Compressibility", 102807728},
    {"_ZN18BatchedNetworkPeer14_receivePacketERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_10shared_ptrINS0_6chrono10time_pointINS9_12steady_clockENS9_8durationIxNS0_5ratioILl1ELl1000000000EEEEEEEEE", 102808144},
    // BedrockLog::LogDetails
    {"_ZN10BedrockLog10LogDetails7_log_vaE9LogAreaIDjPKciiS3_P13__va_list_tag", 226394480},
    // BlockDescriptor::ResolveHelper
    {"_ZN15BlockDescriptor13ResolveHelper7resolveEb", 192626912},
    // BlockType
    {"_ZNK9BlockType14spawnResourcesER11BlockSourceRK8BlockPosRK5BlockR7IRandomRK20ResourceDropsContextPK5Actor", 191415680},
    {"_ZNK9BlockType25tryGetStateFromLegacyDataEt", 191407312},
    // BlockTypeRegistry
    {"_ZNK17BlockTypeRegistry16forEachBlockTypeEN5brstd12function_refIFbRK9BlockTypeES5_EE", 196796432},
    // CampfireBlockActor
    {"_ZN18CampfireBlockActor14_finishCookingER11BlockSourcei", 199771552},
    // Command
    {"_ZNK7Command3runERK13CommandOriginR13CommandOutput", 144484608},
    // CommandOriginLoader
    {"_ZN19CommandOriginLoader4loadERK11CompoundTagR11ServerLevel", 143685648},
    // CommandRegistry
    {"_ZN15CommandRegistry13addEnumValuesERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_6vectorIS6_NS4_IS6_EEEE", 143873392},
    {"_ZN15CommandRegistry13registerAliasENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES6_", 143889760},
    {"_ZN15CommandRegistry15registerCommandERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPKc22CommandPermissionLevel11CommandFlagSC_", 143879680},
    {"_ZN15CommandRegistry24registerOverloadInternalERNS_9SignatureERNS_8OverloadE", 143893600},
    {"_ZNK15CommandRegistry14symbolToStringENS_6SymbolE", 143770336},
    {"_ZNK15CommandRegistry26serializeAvailableCommandsEv", 143956128},
    // CommandUtils
    {"_ZN12CommandUtils12getActorNameERK5Actor", 143676960},
    // CraftingDataPacket
    {"_ZN18CraftingDataPacket18prepareFromRecipesERK7Recipesb", 119595008},
    // DedicatedServer
    {"_ZN15DedicatedServer5startERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKN7Bedrock19ActivationArgumentsE", 68784192},
    // Explosion
    {"_ZN9Explosion7explodeER7IRandom", 194123248},
    // FurnaceBlockActor
    {"_ZN17FurnaceBlockActor15getBurnDurationERK13ItemStackBasef", 199554848},
    // InventoryTransaction
    {"_ZN20InventoryTransaction23executeWorldInteractionEPvR6PlayerRK15InventoryAction", 189734608},
    // Item
    {"_ZNK4Item12readUserDataER13ItemStackBaseR10IDataInputR20ReadOnlyBinaryStream", 188989632},
    // ItemInstance
    {"_ZN12ItemInstance7fromTagERK11CompoundTag", 189082368},
    // ItemRegistry
    {"_ZNK12ItemRegistry12lookupByNameERiNSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE", 183834144},
    // ItemStackBase
    {"_ZN13ItemStackBase34_loadBlocksForCanPlaceOnCanDestroyERNSt3__16vectorIPK9BlockTypeNS0_9allocatorIS4_EEEERKNS0_12basic_stringIcNS0_11char_traitsIcEENS5_IcEEEE", 188782704},
    {"_ZN13ItemStackBase8_setItemEib", 188741424},
    // LeavesBlock
    {"_ZN11LeavesBlock10randomTickERN11BlockEvents20BlockRandomTickEventE", 190951088},
    // Level
    {"_ZN5Level4tickEv", 193836976},
    // LiquidBlock
    {"_ZNK11LiquidBlock12_trySpreadToER11BlockSourceRK8BlockPosiS4_h", 190681856},
    // MapDataManager
    {"_ZN14MapDataManager15getMapSavedDataE13ActorUniqueID", 193889136},
    // MinecraftCommands
    {"_ZN17MinecraftCommands14compileCommandERK12HashedStringR13CommandOrigin17CurrentCmdVersionNSt3__18functionIFvRKNS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEEEEE", 144066768},
    {"_ZNK17MinecraftCommands14executeCommandER14CommandContextb", 144013440},
    // MinecraftPackets
    {"_ZN16MinecraftPackets12createPacketE18MinecraftPacketIds", 124184304},
    // Mob
    {"_ZN3Mob9knockbackEP5ActoriffRK19KnockbackParameters", 159339040},
    // NetworkSystem
    {"_ZN13NetworkSystem4sendERK17NetworkIdentifierRK6Packet11SubClientId", 124194528},
    // Pack
    {"_ZN4Pack10createPackERK15IPackIOProviderRK16ResourceLocation8PackType10PackOriginR20IPackManifestFactoryN7Bedrock15NonOwnerPointerIK19IContentKeyProviderEEP16PackSourceReportRKN4Core4PathE", 141689424},
    // PistonBlockActor
    {"_ZN16PistonBlockActor4tickER11BlockSource", 199210960},
    // Player
    {"_ZN6Player10teleportToERK4Vec3biib", 180575664},
    {"_ZN6Player14stopSleepInBedEbb", 180586496},
    {"_ZN6Player15startSleepInBedERK8BlockPos", 180582304},
    {"_ZN6Player17completeUsingItemEv", 180604256},
    {"_ZN6Player4dropERK9ItemStackb", 180712560},
    {"_ZN6Player4takeER5Actorii", 180660880},
    // RakNet::RNS2_Windows_Linux_360
    {"_ZN6RakNet22RNS2_Windows_Linux_36027Send_Windows_Linux_360NoVDPEiPNS_19RNS2_SendParametersEPKcj", 206204480},
    // RakPeerHelper
    {"_ZN13RakPeerHelper11peerStartupEPN6RakNet16RakPeerInterfaceERK20ConnectionDefinitionNS_11PeerPurposeE", 124325216},
    // RepositoryFactory
    {"_ZNK17RepositoryFactory13createSourcesERK23IResourcePackRepository", 141585296},
    // RepositorySources
    {"_ZN17RepositorySources20initializePackSourceER17PackSourceFactory", 141238016},
    // ResourcePackStack
    {"_ZN17ResourcePackStack11deserializeERNSt3__113basic_istreamIcNS0_11char_traitsIcEEEERKN3gsl8not_nullIN7Bedrock15NonOwnerPointerIK23IResourcePackRepositoryEEEENS0_8optionalINS0_12basic_stringIcS3_NS0_9allocatorIcEEEEEE", 141332000},
    // SayCommand
    {"_ZN10SayCommand12_sendMessageERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_8optionalIS6_EES8_RK21CommandOriginIdentityR5Level", 142338784},
    // ScriptModuleMinecraft::ScriptBlockUtils
    {"_ZN21ScriptModuleMinecraft16ScriptBlockUtils21createBlockDescriptorENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_8optionalINS1_13unordered_mapIS7_NS1_7variantIJiS7_bEEENS1_4hashIS7_EENS1_8equal_toIS7_EENS5_INS1_4pairIKS7_SB_EEEEEEEE", 130183184},
    // ServerInstance
    {"_ZN14ServerInstance16initializeServerEO27ServerInstanceInitArguments", 144647504},
    // ServerNetworkHandler
    {"_ZN20ServerNetworkHandler15tryToLoadPlayerER12ServerPlayerRK17ConnectionRequestRK24PlayerAuthenticationInfo", 123686464},
    {"_ZN20ServerNetworkHandler20_validateLoginPacketERK17NetworkIdentifierRK11LoginPacket", 123609088},
    {"_ZN20ServerNetworkHandler24updateServerAnnouncementEv", 123593776},
    {"_ZN20ServerNetworkHandler27disconnectClientWithMessageERK17NetworkIdentifier11SubClientIdN10Connection20DisconnectFailReasonERKNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEENS6_8optionalISC_EE", 123530064},
    // ServerPlayer
    {"_ZN12ServerPlayer15changeDimensionE13DimensionType", 144422720},
    // ServerScoreboard
    {"_ZN16ServerScoreboardC2E23CommandSoftEnumRegistryP12LevelStorageN3gsl8not_nullIN7Bedrock15NonOwnerPointerI19GameplayUserManagerEEEE", 200994224},
    // WeatherManager
    {"_ZN14WeatherManager13updateWeatherEfifi", 193393264},
}};

}  // namespace endstone::runtime

// NOLINTEND
// clang-format on
