// Generated by scripts/dump_symbols.py for BDS 1.26.36 (windows). DO NOT EDIT.
// clang-format off
// NOLINTBEGIN

#pragma once

#include <array>
#include <cstddef>
#include <string_view>
#include <utility>

namespace endstone::runtime {

static constexpr std::array<std::pair<std::string_view, std::size_t>, 61> symbols = {{
    {"BlockState::StateListNode::mHead", 199508112},
    {"Enchant::mEnchants", 199688464},
    // Actor
    {"?teleportTo@Actor@@UEAAXAEBVVec3@@_NHH1@Z", 14389632},
    // ActorFactory
    {"?createSpawnedActor@ActorFactory@@QEAA?AV?$OwnerPtr@VEntityContext@@@@AEBUActorDefinitionIdentifier@@PEAVActor@@AEBVVec3@@AEBVVec2@@@Z", 26979136},
    // BatchedNetworkPeer
    {"?_receivePacket@BatchedNetworkPeer@@MEAA?AW4DataStatus@NetworkPeer@@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$shared_ptr@V?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@@5@@Z", 5598976},
    {"?sendPacket@BatchedNetworkPeer@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4Reliability@NetworkPeer@@W4Compressibility@@@Z", 5598496},
    // BedrockLog::LogDetails
    {"?_log_va@LogDetails@BedrockLog@@AEAAXW4LogAreaID@@IPEBDHH1PEAD@Z", 21811136},
    // BlockDescriptor::ResolveHelper
    {"?resolve@ResolveHelper@BlockDescriptor@@QEAAX_N@Z", 41162448},
    // BlockType
    {"?spawnResources@BlockType@@QEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEAVIRandom@@AEBUResourceDropsContext@@PEBVActor@@@Z", 62024288},
    {"?tryGetStateFromLegacyData@BlockType@@QEBAPEBVBlock@@G@Z", 62014976},
    // BlockTypeRegistry
    {"?forEachBlockType@BlockTypeRegistry@@QEBAXV?$function_ref@$$A6A_NAEBVBlockType@@@Z$$A6A_N0@Z@brstd@@@Z", 42844560},
    // CampfireBlockActor
    {"?_finishCooking@CampfireBlockActor@@AEAAXAEAVBlockSource@@H@Z", 34087616},
    // Command
    {"?run@Command@@QEBAXAEBVCommandOrigin@@AEAVCommandOutput@@@Z", 11201024},
    // CommandOriginLoader
    {"?load@CommandOriginLoader@@SA?AV?$unique_ptr@VCommandOrigin@@U?$default_delete@VCommandOrigin@@@std@@@std@@AEBVCompoundTag@@AEAVServerLevel@@@Z", 11267792},
    // CommandRegistry
    {"?addEnumValues@CommandRegistry@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@3@@Z", 11597472},
    {"?registerAlias@CommandRegistry@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z", 11620144},
    {"?registerCommand@CommandRegistry@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBDW4CommandPermissionLevel@@UCommandFlag@@3@Z", 11606000},
    {"?registerOverloadInternal@CommandRegistry@@AEAAXAEAUSignature@1@AEAUOverload@1@@Z", 11625184},
    {"?serializeAvailableCommands@CommandRegistry@@QEBA?AVAvailableCommandsPacket@@XZ", 11699904},
    {"?symbolToString@CommandRegistry@@AEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VSymbol@1@@Z", 11458640},
    // CommandUtils
    {"?getActorName@CommandUtils@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVActor@@@Z", 11367200},
    // CraftingDataPacket
    {"?prepareFromRecipes@CraftingDataPacket@@SA?AV?$unique_ptr@VCraftingDataPacket@@U?$default_delete@VCraftingDataPacket@@@std@@@std@@AEBVRecipes@@_N@Z", 57615392},
    // DedicatedServer
    {"?start@DedicatedServer@@QEAA?AW4ServerExitCode@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVActivationArguments@Bedrock@@@Z", 683616},
    // Explosion
    {"?explode@Explosion@@QEAA_NAEAVIRandom@@@Z", 17946256},
    // FurnaceBlockActor
    {"?getBurnDuration@FurnaceBlockActor@@SAMAEBVItemStackBase@@M@Z", 78935456},
    // InventoryTransaction
    {"?executeWorldInteraction@InventoryTransaction@@SA?AW4InventoryTransactionError@@PEAXAEAVPlayer@@AEBVInventoryAction@@@Z", 63810272},
    // Item
    {"?readUserData@Item@@UEBAXAEAVItemStackBase@@AEAVIDataInput@@AEAVReadOnlyBinaryStream@@@Z", 25090000},
    // ItemInstance
    {"?fromTag@ItemInstance@@SA?AV1@AEBVCompoundTag@@@Z", 25180448},
    // ItemRegistry
    {"?lookupByName@ItemRegistry@@AEBA?AV?$WeakPtr@VItem@@@@AEAHV?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z", 17473904},
    // ItemStackBase
    {"?_loadBlocksForCanPlaceOnCanDestroy@ItemStackBase@@CA_NAEAV?$vector@PEBVBlockType@@V?$allocator@PEBVBlockType@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z", 24868144},
    {"?_setItem@ItemStackBase@@AEAA_NH_N@Z", 24829296},
    // LeavesBlock
    {"?randomTick@LeavesBlock@@QEBAXAEAVBlockRandomTickEvent@BlockEvents@@@Z", 69882384},
    // Level
    {"?tick@Level@@UEAAXXZ", 18268640},
    // LiquidBlock
    {"?_trySpreadTo@LiquidBlock@@IEBAXAEAVBlockSource@@AEBVBlockPos@@H1E@Z", 69923424},
    // MapDataManager
    {"?_loadMapData@MapDataManager@@IEAAPEAVMapItemSavedData@@AEBUActorUniqueID@@@Z", 18430032},
    // MinecraftCommands
    {"?compileCommand@MinecraftCommands@@QEAAPEAVCommand@@AEBVHashedString@@AEAVCommandOrigin@@W4CurrentCmdVersion@@V?$function@$$A6AXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z@std@@@Z", 11828480},
    {"?executeCommand@MinecraftCommands@@QEBA?AUMCRESULT@@AEAVCommandContext@@_N@Z", 11767184},
    // MinecraftPackets
    {"?createPacket@MinecraftPackets@@SA?AV?$shared_ptr@VPacket@@@std@@W4MinecraftPacketIds@@@Z", 7180160},
    // Mob
    {"?knockback@Mob@@UEAAXPEAVActor@@HMMAEBUKnockbackParameters@@@Z", 31927648},
    // NetworkSystem
    {"?send@NetworkSystem@@QEAAXAEBVNetworkIdentifier@@AEBVPacket@@W4SubClientId@@@Z", 7191616},
    // PistonBlockActor
    {"?tick@PistonBlockActor@@UEAAXAEAVBlockSource@@@Z", 79036160},
    // Player
    {"?completeUsingItem@Player@@QEAAXXZ", 16916464},
    {"?drop@Player@@UEAA_NAEBVItemStack@@_N@Z", 17016912},
    {"?startSleepInBed@Player@@UEAA?AW4BedSleepingResult@@AEBVBlockPos@@@Z", 16894224},
    {"?stopSleepInBed@Player@@UEAAX_N0@Z", 16898688},
    {"?take@Player@@QEAA_NAEAVActor@@HH@Z", 16966752},
    {"?teleportTo@Player@@UEAAXAEBVVec3@@_NHH1@Z", 16888528},
    // RakNet::RNS2_Windows_Linux_360
    {"?Send_Windows_Linux_360NoVDP@RNS2_Windows_Linux_360@RakNet@@KAHHPEAURNS2_SendParameters@2@PEBDI@Z", 72993536},
    // RakPeerHelper
    {"?peerStartup@RakPeerHelper@@QEAA?AW4StartupResult@RakNet@@PEAVRakPeerInterface@3@AEBUConnectionDefinition@@W4PeerPurpose@1@@Z", 7349168},
    // RepositoryFactory
    {"?createSources@RepositoryFactory@@UEBA?AV?$shared_ptr@VRepositorySources@@@std@@AEBVIResourcePackRepository@@@Z", 9586304},
    // SayCommand
    {"?_sendMessage@SayCommand@@CAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@3@0AEBUCommandOriginIdentity@@AEAVLevel@@@Z", 91591888},
    // ScriptModuleMinecraft::ScriptBlockUtils
    {"?createBlockDescriptor@ScriptBlockUtils@ScriptModuleMinecraft@@YA?AVBlockDescriptor@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$variant@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@2@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$variant@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@2@@std@@@2@@std@@@5@@Z", 94600624},
    // ServerInstance
    {"?initializeServer@ServerInstance@@QEAA_N$$QEAUServerInstanceInitArguments@@@Z", 10894544},
    // ServerNetworkHandler
    {"?_validateLoginPacket@ServerNetworkHandler@@EEAA?AV?$optional@UPlayerAuthenticationInfo@@@std@@AEBVNetworkIdentifier@@AEBVLoginPacket@@@Z", 7645328},
    {"?disconnectClientWithMessage@ServerNetworkHandler@@QEAAXAEBVNetworkIdentifier@@W4SubClientId@@W4DisconnectFailReason@Connection@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@7@@Z", 7557712},
    {"?tryToLoadPlayer@ServerNetworkHandler@@QEAA_NAEAVServerPlayer@@AEBVConnectionRequest@@AEBUPlayerAuthenticationInfo@@@Z", 7739104},
    {"?updateServerAnnouncement@ServerNetworkHandler@@QEAAXXZ", 7627616},
    // ServerPlayer
    {"?changeDimension@ServerPlayer@@UEAAXUDimensionType@@@Z", 11128128},
    // ServerScoreboard
    {"??0ServerScoreboard@@QEAA@VCommandSoftEnumRegistry@@PEAVLevelStorage@@V?$not_null@V?$NonOwnerPointer@VGameplayUserManager@@@Bedrock@@@gsl@@@Z", 19767568},
    // WeatherManager
    {"?updateWeather@WeatherManager@@QEAAXMHMH@Z", 104452096},
    // YAAEAVI18n
    {"?getI18n@@YAAEAVI18n@@XZ", 1470912},
}};

}  // namespace endstone::runtime

// NOLINTEND
// clang-format on
