import lazy_loader as lazy

__getattr__, __dir__, __all__ = lazy.attach(
    "endstone._python",
    submod_attrs={
        "inventory": [
            "BookMeta",
            "BookMetaGeneration",
            "ComplexRecipe",
            "CrossbowMeta",
            "EquipmentSlot",
            "ExactIngredient",
            "Inventory",
            "ItemComplexAliasIngredient",
            "ItemFactory",
            "ItemMeta",
            "ItemStack",
            "ItemTagIngredient",
            "ItemType",
            "ItemTypeIngredient",
            "MapMeta",
            "MolangIngredient",
            "PlayerInventory",
            "PotionMeta",
            "Recipe",
            "RecipeIngredient",
            "ShapedRecipe",
            "ShapelessRecipe",
            "SmithingRecipe",
            "SmithingTransformRecipe",
            "SmithingTrimRecipe",
            "UnknownIngredient",
            "WritableBookMeta",
        ],
    },
)
